version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    security_opt:
      - seccomp=unconfined
    networks:
      - app-network
  
  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge